platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig and running flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Fix for gRPC-Core compilation errors
    if target.name == 'gRPC-Core'
      target.build_configurations.each do |config|
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = "NO"
      end
    end

    # Fix for double-quoted include warnings (PromisesObjC, etc)
    target.build_configurations.each do |config|
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end

    target.build_configurations.each do |config|
      ['LIBRARY_SEARCH_PATHS', 'LD_RUNPATH_SEARCH_PATHS'].each do |key|
        if config.build_settings[key]
          if config.build_settings[key].is_a?(Array)
            config.build_settings[key].map! { |path| path.gsub('"$(DT_TOOLCHAIN_DIR)', '"$(TOOLCHAIN_DIR)') }
          elsif config.build_settings[key].is_a?(String)
            config.build_settings[key] = config.build_settings[key].gsub('"$(DT_TOOLCHAIN_DIR)', '"$(TOOLCHAIN_DIR)')
          end
        end
      end
    end
  end
end
